name: rockos-kernel-native

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

env:
  wget_alias: 'wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0'
  ARCH: riscv
  KBUILD_BUILD_USER: builder
  KBUILD_BUILD_HOST: rockos-riscv-builder
  KDEB_COMPRESS: none
  KDEB_CHANGELOG_DIST: unstable

jobs:
  kernel:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: native-eic7700
            cross: riscv64-linux-gnu-
            machine: [ self-hosted, Linux, riscv64, rockos, eswin ]
            run_image: ghcr.io/revyos/revyos-kernel-builder:riscv64-2025.05.20-plucky
            board: win2030
            compiler: riscv64-linux-gnu-gcc-14

          - name: native-eic7702
            cross: riscv64-linux-gnu-
            machine: [ self-hosted, Linux, riscv64, rockos, eswin ]
            run_image: ghcr.io/revyos/revyos-kernel-builder:riscv64-2025.05.20-plucky
            board: eic7702
            compiler: riscv64-linux-gnu-gcc-14

    runs-on: ${{ matrix.machine }}
    container:
      image: ${{ matrix.run_image }}
    env:
      CROSS_COMPILE: ${{ matrix.cross }}
      board: ${{ matrix.board }}
      compiler: ${{ matrix.compiler }}

    steps:
      - name: Checkout kernel
        uses: actions/checkout@v4
        with:
            path: 'kernel'

      - name: Compile Kernel && Install
        run: |
              mkdir -p output
              ${CROSS_COMPILE}gcc -v

              pushd kernel
                export KDEB_PKGVERSION="$(make kernelversion)-$(date "+%Y.%m.%d.%H.%M")+$(git rev-parse --short HEAD)"
                make CC="${compiler}" ${board}_defconfig

                make CC="${compiler}" -j64 bindeb-pkg LOCALVERSION="-${board}"
                make CC="${compiler}" -j64 dtbs

                # Copy deb
                sudo dcmd cp -v ../*.changes ${GITHUB_WORKSPACE}/output

                # record commit-id
                git rev-parse HEAD > kernel-commitid
                sudo cp -v kernel-commitid ${GITHUB_WORKSPACE}/output
              popd

      - name: compress
        run: tar -zcvf rockos-${{ matrix.name }}.tar.gz output

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: rockos-${{ matrix.name }}
          path: rockos-${{ matrix.name }}.tar.gz
          retention-days: 30
